apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: proxmox-main-node
  title: Proxmox Node
  description: Proxmox.
  annotations:
    backstage.io/techdocs-ref: dir:.
    proxmox.io/node-id: pve
    proxmox.io/type: node
spec:
  type: hypervisor
  lifecycle: production
  owner: user:Mossberg1
  system: homelab
  dependencyOf:
    - resource:dell-poweredge-r440