apiVersion: scaffolder.backstage.io/v1beta3
kind: Template

metadata:
  name: c-template
  title: C Project Template
  description: A C template for small c projects
  tags:
    - c
    - recommended

spec:
  owner: user:guest
  type: service

  parameters:
    - title: Project Info
      required:
        - name          
      properties:
        name:           
          title: Project Name
          type: string
          description: Name of the project
          ui:autofocus: true
          ui:options:
            rows: 5     

  steps:
    - id: fetch
      name: Fetch Template
      action: fetch:template
      input:            
        url: ./template
        values:
          name: ${{ parameters.name }}

    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: ${{ parameters.description }}
        repoUrl: github.com?owner=Mossberg1&repo=${{ parameters.name }} 

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}